version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/userdb

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/taskdb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - task-service

volumes:
  mongo-data:
